// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr2bf0BVmTshtaw2nWqdopFspQS-n8o4o',
    appId: '1:1071319888527:android:09c9f9dbcf51ee0dd3f6fa',
    messagingSenderId: '1071319888527',
    projectId: 'vistaflicks',
    storageBucket: 'vistaflicks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcWGMKlVHcrDcUemjrNVj5Airww2HjXw8',
    appId: '1:1071319888527:ios:9e5b113b31586dc5d3f6fa',
    messagingSenderId: '1071319888527',
    projectId: 'vistaflicks',
    storageBucket: 'vistaflicks.firebasestorage.app',
    androidClientId: '1071319888527-16gqmfovmcn1cs9v7a3gqubkp0dc5kmg.apps.googleusercontent.com',
    iosClientId: '1071319888527-62kdhejjent9raao6sor224g4vm245s2.apps.googleusercontent.com',
    iosBundleId: 'com.vistareels.app',
  );

}